### ISSUE TITLE
name 'squeeze_excite_block' is not defined

### ISSUE THREAD

**Issue by wsyjwps1983** [titu1994/MLSTM-FCN#1]
Hi,everyone have this mistake?
I couldn't find this API in the keras APIs & the repository?

**Comment by titu1994** [comment]
Its not part of the Keras API. You can copy the `squeeze_excite_block` from some other script in the repo to that location. Basic copy paste should be fine. 

Could you tell me where this error occurred ?

**Comment by wsyjwps1983** [comment]
I use the  func in the 'acvitivity_model.py'  ;
How to find this func 'squeeze_excite_block'?
I can't find the func in your repo . how to find the func？
