### ISSUE TITLE
MLSTM-FCN/data/occupancy_detect/generate_occupancy_detect_dataset.py这个文件中第9行的mat数据是怎么样的？和UCI下载到的txt数据格式上有什么区别吗？

### ISSUE THREAD

**Issue by JoeyGao1** [titu1994/MLSTM-FCN#2]

**Comment by titu1994** [comment]
The datasets, and the scripts to convert the UCI datasets to .mat files will be released in some time. 
Sorry for the delay. 

For now, here is the script to convert the .txt file to matlab files and the dataset you requested. Please make sure to cite the UCI repository and our paper for using the .mat and .npy files when using the dataset for academia.

[occupancy.zip](https://github.com/titu1994/MLSTM-FCN/files/1688075/occupancy.zip)

**Comment by JoeyGao1** [comment]
I've got that, thanks a lot for your kindness!
