### ISSUE TITLE
Questions about the data set in this paper

### ISSUE THREAD

**Issue by dugzzuli** [titu1994/MLSTM-FCN#4]
Hello, I am Du Wang, a student from China. I have been reading a paper recently and I feel that I have benefited a lot. There is a question I want to ask you. I downloaded the datasets you provided, but found that these datasets are not the same as the UCI database. Most of the data sets you provide are smaller than the original data sets. What is the status of this data set?

**Comment by titu1994** [comment]
Hello. Could you specify which datasets you compared against? There should be no reason that our datasets are smaller.
