### ISSUE TITLE
Can't find Dataset on UCI

### ISSUE THREAD

**Issue by ashutoshsaboo** [titu1994/MLSTM-FCN#5]
Hi @titu1994 and @fazlekarim ,
I was reading through your paper, but can't find most of the datasets online that you've provided with the code (as well as mentioned in the paper about). For instance, I can't find the EEG2 and EEG dataset on UCI, the EEG dataset that I find there is - https://archive.ics.uci.edu/ml/datasets/Epileptic+Seizure+Recognition , which is substantially different from the one's that you've used.

Could you please point me to specific links from the web for those 2 datasets (EEG and EEG2)? Thanks! 👍

**Comment by fazlekarim** [comment]
The dataset we used are all here: https://github.com/titu1994/MLSTM-FCN/releases

Do you want the exact UCI links?

**Comment by ashutoshsaboo** [comment]
Hi, yes as I mentioned, I already found them there. I wanted the exact UCI links for EEG and EEG2 specifically!
Thanks!

**Comment by fazlekarim** [comment]
I believe these were the ones. I will need to verify it on Monday as it is in my work computer. 

EEG: https://archive.ics.uci.edu/ml/machine-learning-databases/00264/
EEG2: https://archive.ics.uci.edu/ml/machine-learning-databases/eeg-mld/

I think these were the scripts I used to convert it to our mat files:
[eeg_eeg2.zip](https://github.com/titu1994/MLSTM-FCN/files/2498589/eeg_eeg2.zip)

hope that helps

**Comment by ashutoshsaboo** [comment]
Hi @fazlekarim @titu1994 , thanks for the link for EEG and EEG2. Unfortunately, I'm also having serious problems in finding the other datasets as mentioned here - https://github.com/titu1994/MLSTM-FCN/releases - on UCI. If possible, could you please share web links to all of them, the 'large' ones as well as the others? 

I'm sorry, I understand that might be a bit tedious, but having the links will really help me to know more about the dataset in detail. I hope you'd be able to help! 😄 

Thanks again in advance! 😃

**Comment by titu1994** [comment]
@ashutoshsaboo All of the datasets that we have linked to on the releases page are available from the sources stated in the paper. The above datasets from UCI are available there as well. 

Unfortunately, we are currently busy with our respective research projects, and therefore won't be able to help you locate the remaining datasets.

I am sorry we aren't able to help as much. Try using the search functionality on the UCI archive to obtain the remaining datasets, as per your requirement.
