### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Gerhard-Zhang** [titu1994/MLSTM-FCN#6]
Hello, you did a great job, powerful work!
When I try to study the multivariate time series classification, I find the forms of dataset are so complicated and I don't know how to begin without data.
Most of your dataset's formats are 'mat', but I can't find the data files in the project. I don't know matlab, and the data in UCI are so complicated.
Can you show me the data?
I am particularly grateful for your help.

**Comment by fazlekarim** [comment]
Is this the data you are talking about?

https://github.com/titu1994/MLSTM-FCN/releases

**Comment by Gerhard-Zhang** [comment]
Thank you very much!
I will take a careful study to learn how to use them.
